[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = { version = "0.27.2", default-features = false, features = ["derive"] }
libm = { version = "0.2", default-features = false }

[features]
std = []